"""Versioned structured driving output contract with strict parsing.

Purpose:
    Freeze the Stage 03 output contract shared by the machine-readable JSON
    Schemas under ``configs/contracts/`` (``output_schema_v1.json`` and
    ``output_schema_v2.json``) and all later DriveAlign parsing, verifier,
    and evaluator code. Raw model text is parsed strictly and never repaired:
    unknown fields and illegal enumerations are schema failures, and
    geometric violations beyond the JSON Schema are semantic range failures.
    The one documented envelope rule is markdown fence extraction: a single
    ```json fenced block is unwrapped and retried once, and
    ``ParseResult.extracted_from_fences`` records that this happened.
    Truncated or otherwise invalid text stays a JSON parse failure.

    Version support:
    One contract version binds the prompt, the schema, and (from v3 on) the
    closed-vocabulary tables together; see ``contracts/versions.py``. The
    contract version is the single version number used by parser, prompt,
    runner, and records.
    - v1/v2: free-text ``coarse_position`` and ``behavior`` generated by the
      model (v2 recorded the S03 sanity milestone).
    - v3: closed vocabularies. ``coarse_position`` and ``behavior`` leave the
      generation contract; objects carry ``category`` (nuScenes class set),
      ``motion_state``, and ``risk_factors`` from the versioned vocab tables
      in the contract folder. Before schema validation the parser applies the
      documented synonym tables deterministically: mapped open terms are
      rewritten to canonical terms and recorded in
      ``ParseResult.normalized_terms``; open terms with no table mapping are
      left untouched, recorded in ``ParseResult.unmapped_terms``, and let the
      schema reject them. Generic words such as "vehicle" or "moving" are
      intentionally unmapped (mapping them would be a semantic guess).
    - For v3 with ``image_size`` provided, ``coarse_position`` is derived
      deterministically from each bbox center (nine-grid) and reported in
      ``ParseResult.derived_positions``; it is never part of the generation
      contract and never enters ``to_dict()``.

Startup command:
    This module is a library imported by the Stage 03 structured runner and
    tests. Quick v2 round-trip check from the workspace root:
    ``conda activate autovla_codeclean && PYTHONPATH=DriveAlign/src python -c \
    "import json; from drivealign.contracts.output import parse_structured_output; r = parse_structured_output(json.dumps({'critical_objects': [{'category': 'SUV', 'bbox_2d': [1, 2, 3, 4], 'motion_state': 'parked'}], 'risk_factors': [], 'reasoning': 'clear', 'yield_required': False, 'speed_action': 'KEEP_SPEED'})); print(r.ok, r.output.contract_version, r.normalized_terms)"``
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from enum import Enum
from functools import lru_cache
from typing import Any, Mapping, Sequence


from drivealign.contracts.versions import (
    DEFAULT_CONTRACT_VERSION,
    AVAILABLE_CONTRACT_VERSIONS,
    contract_dir,
    contract_file,
)

SPEED_ACTIONS = ("ACCELERATE", "KEEP_SPEED", "DECELERATE", "STOP")

_COARSE_ROWS = ("top", "middle", "bottom")
_COARSE_COLS = ("left", "center", "right")


@lru_cache(maxsize=None)
def _has_vocab_tables(contract_version: str) -> bool:
    """True when the contract folder carries closed-vocabulary tables."""
    return (contract_dir(contract_version) / "category_vocab.json").is_file()


class OutputErrorCategory(str, Enum):
    """Frozen Stage 03 parser error taxonomy (Stage 03 doc, execution step 4)."""

    GENERATION_FAILURE = "generation_failure"
    JSON_PARSE_FAILURE = "json_parse_failure"
    SCHEMA_FAILURE = "schema_failure"
    SEMANTIC_RANGE_FAILURE = "semantic_range_failure"


@dataclass(frozen=True)
class OutputContractError:
    """One categorized validation failure for a single sample."""

    category: OutputErrorCategory
    message: str
    field: str | None = None


@dataclass(frozen=True)
class CriticalObject:
    """One driving-relevant object with its image-space bbox.

    ``coarse_position`` and ``behavior`` are schema v1 generation fields;
    ``motion_state`` is the schema v2 replacement. ``None`` fields are
    omitted from ``to_dict()`` so the dict stays schema-shaped for the
    version that produced it. Derived v2 positions are not stored here.
    """

    category: str
    bbox_2d: tuple[float, float, float, float]
    motion_state: str | None = None
    coarse_position: str | None = None
    behavior: str | None = None

    def to_dict(self) -> dict[str, Any]:
        """Return the schema-shaped dict for the version that parsed this."""
        payload: dict[str, Any] = {
            "category": self.category,
            "bbox_2d": list(self.bbox_2d),
        }
        if self.motion_state is not None:
            payload["motion_state"] = self.motion_state
        if self.coarse_position is not None:
            payload["coarse_position"] = self.coarse_position
        if self.behavior is not None:
            payload["behavior"] = self.behavior
        return payload


@dataclass(frozen=True)
class StructuredDrivingOutput:
    """The versioned structured output produced by one model call."""

    critical_objects: tuple[CriticalObject, ...]
    risk_factors: tuple[str, ...]
    yield_required: bool
    speed_action: str
    contract_version: str
    reasoning: str | None = None

    def to_dict(self) -> dict[str, Any]:
        """Return the schema-shaped dict without the injected version tag.

        ``reasoning`` is emitted only when the parsing contract version
        carries it (v6 dropped the field from the generation schema).
        """
        payload: dict[str, Any] = {
            "critical_objects": [item.to_dict() for item in self.critical_objects],
            "risk_factors": list(self.risk_factors),
            "yield_required": self.yield_required,
            "speed_action": self.speed_action,
        }
        if self.reasoning is not None:
            payload["reasoning"] = self.reasoning
        return payload


@dataclass(frozen=True)
class ParseResult:
    """Strict parse outcome for one raw model text.

    ``ok`` is True only when ``output`` is not None and ``errors`` is empty.
    ``raw_text`` is echoed back so the caller can trace one sample id through
    raw text, parse result, and validation errors. ``extracted_from_fences``
    is True exactly when the documented markdown-fence envelope rule was
    applied before parsing; content validation is identical either way.
    ``normalized_terms`` lists (open term, canonical term) rewrites applied
    through the versioned synonym tables; ``unmapped_terms`` lists open terms
    no table could map (the schema rejects them). ``derived_positions`` holds
    the v2 nine-grid ``coarse_position`` per object index (None where the
    image size needed for the derivation was not provided).
    """

    ok: bool
    output: StructuredDrivingOutput | None
    errors: tuple[OutputContractError, ...]
    raw_text: str
    contract_version: str
    extracted_from_fences: bool = False
    normalized_terms: tuple[tuple[str, str], ...] = ()
    unmapped_terms: tuple[str, ...] = ()
    derived_positions: tuple[str | None, ...] = ()


def load_output_schema(contract_version: str) -> dict[str, Any]:
    """Load the machine-readable schema of one contract version."""
    path = contract_file(contract_version, "output_schema.json")
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


@lru_cache(maxsize=None)
def _cached_validator(contract_version: str) -> Any:
    from jsonschema import Draft202012Validator

    schema = load_output_schema(contract_version)
    validator = Draft202012Validator(schema)
    validator.check_schema(schema)
    return validator


def _validator_for(contract_version: str) -> Any:
    return _cached_validator(contract_version)


@lru_cache(maxsize=None)
def _vocab_mapping(contract_version: str, filename: str) -> Mapping[str, str]:
    """Load one versioned vocab table as normalized open term -> canonical."""
    path = contract_file(contract_version, filename)
    with path.open("r", encoding="utf-8") as handle:
        vocab = json.load(handle)
    mapping: dict[str, str] = {}
    for term in vocab["terms"]:
        canonical = term["canonical"]
        mapping[_normalize_term(canonical)] = canonical
        for synonym in term["synonyms"]:
            mapping[_normalize_term(synonym)] = canonical
    return mapping


def _normalize_term(term: str) -> str:
    """Lowercase, collapse whitespace, and join words with underscores."""
    return " ".join(term.split()).lower().replace(" ", "_")


def _singularize_words(term: str) -> str:
    """Strip one trailing 's' from every word (best effort, no repair).

    Plurals can appear on any word of a multi-word synonym, e.g.
    "Pedestrians crossing" -> "pedestrian_crossing". A failed guess simply
    stays unmapped, so over-stripping is harmless.
    """
    parts = []
    for word in term.split("_"):
        if word.endswith("s") and len(word) > 2 and not word.endswith("ss"):
            parts.append(word[:-1])
        else:
            parts.append(word)
    return "_".join(parts)


def _canonicalize_term(term: str, mapping: Mapping[str, str]) -> str | None:
    """Map one open term through the vocab table; None when unmapped."""
    normalized = _normalize_term(term)
    if normalized in mapping:
        return mapping[normalized]
    singular = _singularize_words(normalized)
    if singular != normalized and singular in mapping:
        return mapping[singular]
    return None


def _normalize_v2_payload(
    contract_version: str, payload: Any
) -> tuple[Any, tuple[tuple[str, str], ...], tuple[str, ...]]:
    """Rewrite open vocabulary terms in a v2 payload via the synonym tables.

    Returns the (possibly rewritten) payload plus the traceability lists.
    Unmapped terms are left untouched for the schema to reject; nothing is
    ever silently dropped or guessed.
    """
    if not isinstance(payload, dict):
        return payload, (), ()
    normalized_terms: list[tuple[str, str]] = []
    unmapped_terms: list[str] = []
    rewritten = dict(payload)

    category_map = _vocab_mapping(contract_version, "category_vocab.json")
    motion_map = _vocab_mapping(contract_version, "motion_vocab.json")
    risk_map = _vocab_mapping(contract_version, "risk_taxonomy.json")

    objects = rewritten.get("critical_objects")
    if isinstance(objects, list):
        fixed_objects = []
        for item in objects:
            if not isinstance(item, dict):
                fixed_objects.append(item)
                continue
            fixed = dict(item)
            for key, mapping in (("category", category_map), ("motion_state", motion_map)):
                value = fixed.get(key)
                if isinstance(value, str):
                    canonical = _canonicalize_term(value, mapping)
                    if canonical is not None and canonical != value:
                        normalized_terms.append((value, canonical))
                        fixed[key] = canonical
                    elif canonical is None:
                        unmapped_terms.append(value)
            fixed_objects.append(fixed)
        rewritten["critical_objects"] = fixed_objects

    risks = rewritten.get("risk_factors")
    if isinstance(risks, list):
        fixed_risks = []
        for value in risks:
            if not isinstance(value, str):
                fixed_risks.append(value)
                continue
            canonical = _canonicalize_term(value, risk_map)
            if canonical is not None:
                if canonical != value:
                    normalized_terms.append((value, canonical))
                fixed_risks.append(canonical)
            else:
                unmapped_terms.append(value)
                fixed_risks.append(value)
        rewritten["risk_factors"] = fixed_risks

    return rewritten, tuple(normalized_terms), tuple(unmapped_terms)


def _format_path(absolute_path: Sequence[Any]) -> str | None:
    """Format a jsonschema absolute path as a JSON pointer-like field name."""
    if not absolute_path:
        return None
    field = "$"
    for part in absolute_path:
        field += f"[{part}]" if isinstance(part, int) else f".{part}"
    return field


def _build_critical_object(payload: Mapping[str, Any]) -> CriticalObject:
    bbox = payload["bbox_2d"]
    return CriticalObject(
        category=payload["category"],
        bbox_2d=(float(bbox[0]), float(bbox[1]), float(bbox[2]), float(bbox[3])),
        motion_state=payload.get("motion_state"),
        coarse_position=payload.get("coarse_position"),
        behavior=payload.get("behavior"),
    )


def _derive_coarse_position(
    bbox: tuple[float, float, float, float], image_size: Sequence[float]
) -> str:
    """Deterministic nine-grid position from the bbox center."""
    width, height = float(image_size[0]), float(image_size[1])
    center_x = (bbox[0] + bbox[2]) / 2.0
    center_y = (bbox[1] + bbox[3]) / 2.0
    col = _COARSE_COLS[min(2, int(center_x / (width / 3.0)))]
    row = _COARSE_ROWS[min(2, int(center_y / (height / 3.0)))]
    return f"{row} {col}"


def _semantic_errors(output: StructuredDrivingOutput, image_size: Sequence[float] | None) -> list[OutputContractError]:
    """Check geometric rules that the JSON Schema cannot express."""
    errors: list[OutputContractError] = []
    for index, item in enumerate(output.critical_objects):
        x_min, y_min, x_max, y_max = item.bbox_2d
        if x_min > x_max or y_min > y_max:
            errors.append(
                OutputContractError(
                    category=OutputErrorCategory.SEMANTIC_RANGE_FAILURE,
                    message=(
                        f"bbox_2d corners are unordered: got "
                        f"[{x_min}, {y_min}, {x_max}, {y_max}]"
                    ),
                    field=f"$.critical_objects[{index}].bbox_2d",
                )
            )
        if image_size is not None:
            width, height = float(image_size[0]), float(image_size[1])
            if x_max > width or y_max > height:
                errors.append(
                    OutputContractError(
                        category=OutputErrorCategory.SEMANTIC_RANGE_FAILURE,
                        message=(
                            f"bbox_2d exceeds image bounds "
                            f"[{x_max}, {y_max}] > [{width}, {height}]"
                        ),
                        field=f"$.critical_objects[{index}].bbox_2d",
                    )
                )
    return errors


_FENCED_ENVELOPE = re.compile(
    r"^\s*```(?:json)?\s*\n(?P<body>.*)\n\s*```\s*$",
    re.DOTALL,
)


def _json_loads(text: str) -> tuple[Any, Exception | None]:
    try:
        return json.loads(text), None
    except (json.JSONDecodeError, TypeError, ValueError) as exc:
        return None, exc


def parse_structured_output(
    raw_text: str,
    *,
    contract_version: str | None = None,
    image_size: Sequence[float] | None = None,
) -> ParseResult:
    """Parse one raw model text strictly against one contract version.

    ``contract_version`` (default ``DEFAULT_CONTRACT_VERSION``) selects the
    frozen prompt/schema/vocab pairing from ``configs/contracts/v<N>/``. The
    parser performs no content repair: it never trims trailing text, drops
    unknown fields, or invents values. The two documented preprocessing rules
    are the markdown fence envelope (recorded in ``extracted_from_fences``)
    and, for contracts carrying vocab tables, the synonym-table normalization
    (recorded term by term in ``normalized_terms``/``unmapped_terms``).
    ``image_size`` optionally enables the image-bounds semantic check and the
    deterministic ``coarse_position`` derivation.
    """
    version = contract_version if contract_version is not None else DEFAULT_CONTRACT_VERSION
    if version not in AVAILABLE_CONTRACT_VERSIONS:
        raise ValueError(
            f"Unknown contract version {version!r}; "
            f"available: {', '.join(AVAILABLE_CONTRACT_VERSIONS)}"
        )

    def _fail(
        errors: tuple[OutputContractError, ...],
        raw: str,
        extracted: bool = False,
    ) -> ParseResult:
        return ParseResult(
            ok=False,
            output=None,
            errors=errors,
            raw_text=raw,
            contract_version=version,
            extracted_from_fences=extracted,
        )

    if raw_text is None or isinstance(raw_text, (dict, list)):
        return _fail(
            (
                OutputContractError(
                    category=OutputErrorCategory.JSON_PARSE_FAILURE,
                    message="Raw text is not a JSON string",
                ),
            ),
            "" if raw_text is None else str(raw_text),
        )

    payload, parse_error = _json_loads(raw_text)
    extracted = False
    fence_attempted = False
    if payload is None and isinstance(raw_text, str):
        fence = _FENCED_ENVELOPE.match(raw_text)
        if fence is not None:
            fence_attempted = True
            inner_payload, inner_error = _json_loads(fence.group("body"))
            if inner_payload is not None:
                payload, extracted = inner_payload, True
            else:
                parse_error = inner_error

    if payload is None:
        suffix = " after fence extraction" if fence_attempted else ""
        hint = ""
        if isinstance(raw_text, str) and not raw_text.rstrip().endswith("}"):
            hint = (
                " (raw text does not end with '}': output looks truncated, "
                "check the generation token budget)"
            )
        return _fail(
            (
                OutputContractError(
                    category=OutputErrorCategory.JSON_PARSE_FAILURE,
                    message=f"Raw text is not valid JSON{suffix}: {parse_error}{hint}",
                ),
            ),
            raw_text,
            extracted,
        )

    normalized_terms: tuple[tuple[str, str], ...] = ()
    unmapped_terms: tuple[str, ...] = ()
    if _has_vocab_tables(version):
        payload, normalized_terms, unmapped_terms = _normalize_v2_payload(
            version, payload
        )

    validator = _validator_for(version)
    schema_errors = tuple(
        OutputContractError(
            category=OutputErrorCategory.SCHEMA_FAILURE,
            message=error.message,
            field=_format_path(error.absolute_path),
        )
        for error in validator.iter_errors(payload)
    )
    if schema_errors:
        return ParseResult(
            ok=False,
            output=None,
            errors=schema_errors,
            raw_text=raw_text,
            contract_version=version,
            extracted_from_fences=extracted,
            normalized_terms=normalized_terms,
            unmapped_terms=unmapped_terms,
        )

    output = StructuredDrivingOutput(
        critical_objects=tuple(
            _build_critical_object(item)
            for item in payload["critical_objects"]
        ),
        risk_factors=tuple(payload["risk_factors"]),
        yield_required=payload["yield_required"],
        speed_action=payload["speed_action"],
        contract_version=version,
        reasoning=payload.get("reasoning"),
    )

    semantic = tuple(_semantic_errors(output, image_size))
    if semantic:
        return ParseResult(
            ok=False,
            output=None,
            errors=semantic,
            raw_text=raw_text,
            contract_version=version,
            extracted_from_fences=extracted,
            normalized_terms=normalized_terms,
            unmapped_terms=unmapped_terms,
        )

    derived: tuple[str | None, ...] = ()
    if _has_vocab_tables(version):
        derived = tuple(
            _derive_coarse_position(item.bbox_2d, image_size)
            if image_size is not None
            else None
            for item in output.critical_objects
        )

    return ParseResult(
        ok=True,
        output=output,
        errors=(),
        raw_text=raw_text,
        contract_version=version,
        extracted_from_fences=extracted,
        normalized_terms=normalized_terms,
        unmapped_terms=unmapped_terms,
        derived_positions=derived,
    )
